import type { BoardProfile } from '../domain';

export const builtInBoardProfiles: BoardProfile[] = [
  {
    id: 'raspberry-pi-4-model-b',
    name: 'Raspberry Pi 4 Model B',
    family: 'Raspberry Pi',
    source: 'built_in',
    notes: 'Common 85 x 56 mm Raspberry Pi mounting pattern with USB/Ethernet side clearance starter cutouts.',
    pcb: {
      width: 85,
      height: 56,
      thickness: 1.6,
      componentHeight: 14,
      cornerRadius: 3,
      mountingHoles: [
        { id: 'mh-1', x: 3.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-2', x: 61.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-3', x: 3.5, y: 52.5, diameter: 2.75 },
        { id: 'mh-4', x: 61.5, y: 52.5, diameter: 2.75 },
      ],
      connectorCutouts: [
        { id: 'cutout-usb-ethernet', label: 'USB/Ethernet', side: 'right', offset: 34, z: 10, width: 38, height: 14 },
        { id: 'cutout-usbc-power', label: 'USB-C power', side: 'front', offset: 12, z: 7, width: 10, height: 4 },
        { id: 'cutout-hdmi', label: 'Micro HDMI', side: 'front', offset: 31, z: 7, width: 18, height: 4 },
      ],
    },
  },
  {
    id: 'raspberry-pi-5',
    name: 'Raspberry Pi 5',
    family: 'Raspberry Pi',
    source: 'built_in',
    notes: 'Raspberry Pi 5 mechanical envelope with common mounting pattern. Verify fan, power button, and FFC clearances for the exact board revision.',
    pcb: {
      width: 85,
      height: 56,
      thickness: 1.6,
      componentHeight: 14,
      cornerRadius: 3,
      mountingHoles: [
        { id: 'mh-1', x: 3.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-2', x: 61.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-3', x: 3.5, y: 52.5, diameter: 2.75 },
        { id: 'mh-4', x: 61.5, y: 52.5, diameter: 2.75 },
      ],
      connectorCutouts: [
        { id: 'cutout-usb-ethernet', label: 'USB/Ethernet', side: 'right', offset: 35, z: 10, width: 39, height: 14 },
        { id: 'cutout-usbc-power', label: 'USB-C power', side: 'front', offset: 12, z: 7, width: 10, height: 4 },
        { id: 'cutout-micro-hdmi-a', label: 'Micro HDMI 1', side: 'front', offset: 29, z: 7, width: 10, height: 4 },
        { id: 'cutout-micro-hdmi-b', label: 'Micro HDMI 2', side: 'front', offset: 43, z: 7, width: 10, height: 4 },
      ],
    },
  },
  {
    id: 'raspberry-pi-zero-2-w',
    name: 'Raspberry Pi Zero 2 W',
    family: 'Raspberry Pi',
    source: 'built_in',
    notes: 'Pi Zero family envelope with micro USB, mini HDMI, and corner mounting holes.',
    pcb: {
      width: 65,
      height: 30,
      thickness: 1.6,
      componentHeight: 5,
      cornerRadius: 3,
      mountingHoles: [
        { id: 'mh-1', x: 3.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-2', x: 61.5, y: 3.5, diameter: 2.75 },
        { id: 'mh-3', x: 3.5, y: 26.5, diameter: 2.75 },
        { id: 'mh-4', x: 61.5, y: 26.5, diameter: 2.75 },
      ],
      connectorCutouts: [
        { id: 'cutout-micro-usb-power', label: 'Micro USB power', side: 'front', offset: 39, z: 6, width: 9, height: 4 },
        { id: 'cutout-mini-hdmi', label: 'Mini HDMI', side: 'front', offset: 13, z: 6, width: 12, height: 5 },
      ],
    },
  },
  {
    id: 'raspberry-pi-pico',
    name: 'Raspberry Pi Pico',
    family: 'Raspberry Pi',
    source: 'built_in',
    notes: 'Pico-style 51 x 21 mm module with USB end opening and four corner mounting holes.',
    pcb: {
      width: 51,
      height: 21,
      thickness: 1.6,
      componentHeight: 4,
      cornerRadius: 1,
      mountingHoles: [
        { id: 'mh-1', x: 2, y: 2, diameter: 2.1 },
        { id: 'mh-2', x: 49, y: 2, diameter: 2.1 },
        { id: 'mh-3', x: 2, y: 19, diameter: 2.1 },
        { id: 'mh-4', x: 49, y: 19, diameter: 2.1 },
      ],
      connectorCutouts: [
        { id: 'cutout-micro-usb', label: 'Micro USB', side: 'front', offset: 25.5, z: 6, width: 9, height: 4 },
      ],
    },
  },
  {
    id: 'arduino-uno-r3',
    name: 'Arduino Uno R3',
    family: 'Arduino',
    source: 'built_in',
    notes: 'Uno R3 board envelope with asymmetric mounting holes and USB-B / barrel-jack starter cutouts.',
    pcb: {
      width: 68.6,
      height: 53.4,
      thickness: 1.6,
      componentHeight: 12,
      cornerRadius: 2,
      mountingHoles: [
        { id: 'mh-1', x: 14, y: 2.5, diameter: 3.2 },
        { id: 'mh-2', x: 66.1, y: 7.6, diameter: 3.2 },
        { id: 'mh-3', x: 66.1, y: 35.5, diameter: 3.2 },
        { id: 'mh-4', x: 15.3, y: 50.8, diameter: 3.2 },
      ],
      connectorCutouts: [
        { id: 'cutout-usb-b', label: 'USB-B', side: 'front', offset: 17, z: 9, width: 13, height: 12 },
        { id: 'cutout-barrel-jack', label: 'Barrel jack', side: 'front', offset: 38, z: 9, width: 11, height: 11 },
      ],
    },
  },
  {
    id: 'arduino-mega-2560-r3',
    name: 'Arduino Mega 2560 R3',
    family: 'Arduino',
    source: 'built_in',
    notes: 'Mega 2560 R3 board envelope with starter USB-B and barrel-jack openings. Verify shield/header height for stacked builds.',
    pcb: {
      width: 101.52,
      height: 53.3,
      thickness: 1.6,
      componentHeight: 12,
      cornerRadius: 2,
      mountingHoles: [
        { id: 'mh-1', x: 13.97, y: 2.54, diameter: 3.2 },
        { id: 'mh-2', x: 66.04, y: 7.62, diameter: 3.2 },
        { id: 'mh-3', x: 66.04, y: 35.56, diameter: 3.2 },
        { id: 'mh-4', x: 15.24, y: 50.8, diameter: 3.2 },
      ],
      connectorCutouts: [
        { id: 'cutout-usb-b', label: 'USB-B', side: 'front', offset: 17, z: 9, width: 13, height: 12 },
        { id: 'cutout-barrel-jack', label: 'Barrel jack', side: 'front', offset: 38, z: 9, width: 11, height: 11 },
      ],
    },
  },
  {
    id: 'arduino-nano',
    name: 'Arduino Nano',
    family: 'Arduino',
    source: 'built_in',
    notes: 'Nano-class module envelope. Many variants omit mounting holes, so this profile starts without holes.',
    pcb: {
      width: 45,
      height: 18,
      thickness: 1.6,
      componentHeight: 4,
      cornerRadius: 1,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-mini-usb', label: 'USB', side: 'front', offset: 22.5, z: 6, width: 9, height: 4 },
      ],
    },
  },
  {
    id: 'esp32-devkit-v1',
    name: 'ESP32 DevKit V1',
    family: 'ESP32',
    source: 'built_in',
    notes: 'Common ESP32 DevKit envelope with USB opening. Verify width against clone variants before printing.',
    pcb: {
      width: 55,
      height: 28,
      thickness: 1.6,
      componentHeight: 4,
      cornerRadius: 1,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-micro-usb', label: 'Micro USB', side: 'front', offset: 27.5, z: 6, width: 9, height: 4 },
      ],
    },
  },
  {
    id: 'esp32-s3-devkitc-1',
    name: 'ESP32-S3-DevKitC-1',
    family: 'ESP32',
    source: 'built_in',
    notes: 'Common ESP32-S3-DevKitC-1 envelope with USB-C opening. Clone widths and antenna clearances vary.',
    pcb: {
      width: 55,
      height: 28,
      thickness: 1.6,
      componentHeight: 5,
      cornerRadius: 1,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-usb-c', label: 'USB-C', side: 'front', offset: 27.5, z: 6, width: 10, height: 4 },
      ],
    },
  },
  {
    id: 'beaglebone-black',
    name: 'BeagleBone Black',
    family: 'BeagleBone',
    source: 'built_in',
    notes: 'BeagleBone Black mechanical envelope. Header, Ethernet, USB, and barrel-jack clearances should be checked against the exact revision.',
    pcb: {
      width: 86.36,
      height: 53.34,
      thickness: 1.6,
      componentHeight: 13,
      cornerRadius: 2,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-ethernet', label: 'Ethernet', side: 'right', offset: 38, z: 10, width: 16, height: 14 },
        { id: 'cutout-usb-a', label: 'USB-A host', side: 'right', offset: 18, z: 9, width: 14, height: 8 },
        { id: 'cutout-mini-usb', label: 'Mini USB', side: 'front', offset: 28, z: 6, width: 9, height: 4 },
        { id: 'cutout-barrel-jack', label: 'Barrel jack', side: 'front', offset: 54, z: 8, width: 11, height: 11 },
      ],
    },
  },
  {
    id: 'nvidia-jetson-orin-nano-devkit-carrier',
    name: 'NVIDIA Jetson Orin Nano DevKit Carrier',
    family: 'NVIDIA Jetson',
    source: 'built_in',
    notes: 'Developer kit carrier board mechanical envelope. Height includes module/thermal clearance starter value; verify heatsink and fan stack.',
    pcb: {
      width: 100,
      height: 79,
      thickness: 1.57,
      componentHeight: 21,
      cornerRadius: 2,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-usb-stack', label: 'USB stack', side: 'right', offset: 40, z: 11, width: 32, height: 16 },
        { id: 'cutout-ethernet', label: 'Ethernet', side: 'right', offset: 66, z: 11, width: 16, height: 14 },
        { id: 'cutout-dc-jack', label: 'DC jack', side: 'front', offset: 18, z: 9, width: 12, height: 11 },
        { id: 'cutout-displayport', label: 'DisplayPort', side: 'front', offset: 48, z: 8, width: 16, height: 6 },
      ],
    },
  },
  {
    id: 'm5stack-core2',
    name: 'M5Stack Core2',
    family: 'M5Stack',
    source: 'built_in',
    notes: 'Core2 module envelope profile for accessory shells and mounts rather than a bare PCB.',
    pcb: {
      width: 54,
      height: 54,
      thickness: 1.6,
      componentHeight: 15,
      cornerRadius: 5,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-usb-c', label: 'USB-C', side: 'front', offset: 27, z: 8, width: 10, height: 4 },
      ],
    },
  },
  {
    id: 'hackrf-one',
    name: 'HackRF One',
    family: 'SDR',
    source: 'built_in',
    notes: 'HackRF One board-envelope starter profile with USB and SMA edge openings. Verify RF connector stack height before printing.',
    pcb: {
      width: 120,
      height: 75,
      thickness: 1.6,
      componentHeight: 12,
      cornerRadius: 2,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-micro-usb', label: 'Micro USB', side: 'front', offset: 60, z: 7, width: 9, height: 4 },
        { id: 'cutout-sma-1', label: 'SMA 1', side: 'back', offset: 30, z: 8, width: 8, height: 8 },
        { id: 'cutout-sma-2', label: 'SMA 2', side: 'back', offset: 90, z: 8, width: 8, height: 8 },
      ],
    },
  },
  {
    id: 'limesdr-mini',
    name: 'LimeSDR Mini',
    family: 'SDR',
    source: 'built_in',
    notes: 'LimeSDR Mini envelope with USB and dual SMA starter openings. Board revisions vary; confirm connector offsets.',
    pcb: {
      width: 69,
      height: 31.4,
      thickness: 1.6,
      componentHeight: 7,
      cornerRadius: 1,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-usb-a', label: 'USB', side: 'front', offset: 34.5, z: 7, width: 14, height: 8 },
        { id: 'cutout-sma-1', label: 'SMA RX', side: 'back', offset: 18, z: 7, width: 8, height: 8 },
        { id: 'cutout-sma-2', label: 'SMA TX', side: 'back', offset: 51, z: 7, width: 8, height: 8 },
      ],
    },
  },
  {
    id: 'rtl-sdr-blog-v3',
    name: 'RTL-SDR Blog V3',
    family: 'SDR',
    source: 'built_in',
    notes: 'USB dongle envelope for carrier/adapter enclosures. Treat as a module profile, not a bare PCB drawing.',
    pcb: {
      width: 69,
      height: 27,
      thickness: 1.6,
      componentHeight: 12,
      cornerRadius: 2,
      mountingHoles: [],
      connectorCutouts: [
        { id: 'cutout-usb-a', label: 'USB-A plug', side: 'front', offset: 13, z: 7, width: 14, height: 8 },
        { id: 'cutout-sma', label: 'SMA', side: 'back', offset: 13, z: 7, width: 8, height: 8 },
      ],
    },
  },
];

export function boardProfileById(id: string): BoardProfile | undefined {
  return builtInBoardProfiles.find((profile) => profile.id === id);
}
