import type { MaterialId, MaterialProfile } from './types';

export const materialProfiles: Record<MaterialId, MaterialProfile> = {
  pla: {
    id: 'pla',
    name: 'PLA',
    clearance: 0.25,
    snapFitClearance: 0.35,
    holeCompensation: 0.15,
    wallThickness: 1.6,
    minimumFeatureSize: 0.8,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 15,
    bambuProfileHint: '0.20mm Standard @BBL X1C / P1S, PLA Basic',
  },
  petg: {
    id: 'petg',
    name: 'PETG',
    clearance: 0.35,
    snapFitClearance: 0.45,
    holeCompensation: 0.2,
    wallThickness: 1.8,
    minimumFeatureSize: 0.9,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 20,
    bambuProfileHint: '0.20mm Strength @BBL X1C / P1S, PETG Basic',
  },
  abs: {
    id: 'abs',
    name: 'ABS',
    clearance: 0.4,
    snapFitClearance: 0.5,
    holeCompensation: 0.25,
    wallThickness: 2,
    minimumFeatureSize: 1,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 20,
    bambuProfileHint: '0.20mm Strength, enclosed printer, ABS',
  },
  asa: {
    id: 'asa',
    name: 'ASA',
    clearance: 0.4,
    snapFitClearance: 0.5,
    holeCompensation: 0.25,
    wallThickness: 2,
    minimumFeatureSize: 1,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 20,
    bambuProfileHint: '0.20mm Strength, enclosed printer, ASA',
  },
  tpu: {
    id: 'tpu',
    name: 'TPU',
    clearance: 0.5,
    snapFitClearance: 0.7,
    holeCompensation: 0.3,
    wallThickness: 2.4,
    minimumFeatureSize: 1.2,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 12,
    bambuProfileHint: '0.20mm Standard, TPU 95A',
  },
  cf_pla: {
    id: 'cf_pla',
    name: 'Carbon Fiber PLA',
    clearance: 0.3,
    snapFitClearance: 0.45,
    holeCompensation: 0.2,
    wallThickness: 1.8,
    minimumFeatureSize: 0.9,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 15,
    bambuProfileHint: '0.20mm Strength, hardened nozzle, PLA-CF',
  },
  nylon: {
    id: 'nylon',
    name: 'Nylon',
    clearance: 0.45,
    snapFitClearance: 0.6,
    holeCompensation: 0.25,
    wallThickness: 2.2,
    minimumFeatureSize: 1.1,
    recommendedLayerHeight: 0.2,
    recommendedInfillPercent: 25,
    bambuProfileHint: '0.20mm Strength, dried filament, PA / PA-CF',
  },
};

export function getMaterialProfile(id: MaterialId): MaterialProfile {
  return materialProfiles[id];
}
